export { default as Home } from "./Home";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as ForgotPassword } from "./ForgotPassword";
export { default as Dashboard } from "./Dashboard";
export { default as Products } from "./Products";
export { default as ProductDetail } from "./ProductDetail";
export { default as Profile } from "./Profile";
export { default as Favorites } from "./Favorites";
export { default as History } from "./History";
export { default as HistoryDetail } from "./HistoryDetail";
export { default as NotFound } from "./NotFound";
export { default as ArticleDetail } from "./ArticleDetail";
export { default as Articles } from "./Articles";
export { default as Scanner } from "./Scanner";
export { About, FAQ, Contact, Privacy, Terms } from "./StaticPages";
